runtime: python
service: default
env: flex
entrypoint: gunicorn -b :$PORT biangelis.wsgi

manual_scaling:
      instances: 1

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.12"