# Generated by Django 6.0.2 on 2026-03-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='portfolio_app/static/images/placeholder.png', null=True, upload_to='portfolio_app/static/post_img'),
        ),
    ]
