# Generated by Django 6.0.2 on 2026-03-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repo_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
