# Generated by Django 6.0.2 on 2026-03-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_post_repo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
